apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: salome-jobs
  namespace: salome
spec:
  accessModes:
    - ReadWriteMany    # Jobs written by one pod must be readable by any pod
  storageClassName: efs-salome
  resources:
    requests:
      storage: 200Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: salome-bundles
  namespace: salome
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-salome
  resources:
    requests:
      storage: 100Gi
