[backend]
backend-server ansible_host=34.47.101.190 ansible_user=mateen_fastians
backend-aws-prod ansible_host=3.35.138.242 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[salome]
salome-server ansible_host=34.47.115.135 ansible_user=mateen_fastians
salome-aws-prod ansible_host=13.209.14.89 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[monitoring]
monitoring-server
