apiVersion: 1

contactPoints:
  - orgId: 1
    name: Default
    receivers:
      - uid: default-receiver
        type: email
        disableResolveMessage: false
        settings:
          addresses: "noreply@localhost"
